export enum NaigatorTypes {
    //taskList
    TASK_LIST_NORMAL = 'TASK_LIST_NORMAL',
    //contactList
    CONTACT_LIST_BASE = 'CONTACT_LIST_BASE',
    CONTACT_LIST_BUILDER = 'CONTACT_LIST_BUILDER',
    CONTACT_LIST_DETAIL = 'CONTACT_LIST_DETAIL',
    CONTACT_LIST_APPROVE = 'CONTACT_LIST_APPROVE',
    //staffList
    STAFF_LIST_NORMAL = 'STAFF_LIST_NORMAL',
    STAFF_LIST_CONTACT = 'STAFF_LIST_CONTACT',
}